; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino

upload_protocol = espota
upload_port = 192.168.0.244

monitor_speed = 115200
lib_deps =
  m5stack/M5Unified@^0.1.16
  meganetaaan/M5Stack-Avatar@^0.8.2
	robotis-git/Dynamixel2Arduino@^0.7.0
	gob/gob_unifiedButton
	adafruit/Adafruit AW9523@^1.0.5
  https://github.com/micro-ROS/micro_ros_platformio

board_microros_distro = humble
board_microros_transport = wifi
build_flags =
  -std=gnu++17
  -DMICRO_ROS_TRANSPORT_UDP
  -DARDUINOJSON_ENABLE_ARDUINO_STRING=1
  -DARDUINOJSON_USE_LONG_LONG=1
  -DARDUINOJSON_DECODE_UNICODE=1
  -DARDUINOJSON_ENABLE_NAN=1
