; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = esp32s3box
framework = arduino
; upload_protocol = espota
; upload_port = 192.168.0.244
board_build.arduino.memory_type = qio_qspi ; この行を指定しないとCoreS3では動かない。
board_build.arduino.partitions = default_16MB.csv  ; flashを16MBフルで使えるようにする。
upload_speed = 1500000
monitor_speed = 115200
board_build.filesystem = spiffs
; board_build.f_cpu = 240000000L       ;240M(WiFi OK), 160M(WiFi OK), 80M(WiFi OK), 40M, 20M, 10M
; build_unflags = -Os

board_microros_distro = humble
board_microros_transport = wifi
build_flags =
	; -O3
	-std=gnu++17
  -DCORE_DEBUG_LEVEL=5
  -DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DMICRO_ROS_TRANSPORT_UDP
	-DARDUINOJSON_ENABLE_ARDUINO_STRING=1
	-DARDUINOJSON_USE_LONG_LONG=1
	-DARDUINOJSON_DECODE_UNICODE=1
	-DARDUINOJSON_ENABLE_NAN=1

lib_deps =
	m5stack/M5Unified@^0.1.16
	meganetaaan/M5Stack-Avatar@^0.8.2
	robotis-git/Dynamixel2Arduino@^0.7.0
	gob/gob_unifiedButton
	adafruit/Adafruit AW9523@^1.0.5
	https://github.com/micro-ROS/micro_ros_platformio
	arduino-libraries/Madgwick@^1.2.0
  esp32-camera
lib_ldf_mode = deep